### ISSUE TITLE
Spilt resolver files

### ISSUE THREAD

**Issue by KoichiKiyokawa** [uhyo/nitrogql#18]
First, thank you for the wonderful library 🎉 
I'd like to split resolvers by feature(user, post, etc...).
The directory structure is as follows:

- schemas
  - user.gql
  - post.gql
- resolvers
  - user.ts
  - post.ts

Each file is structured as below:
```gql
# schema/user.gql
type User {
  id: ID! @model
  name: String! @model

  posts: [Post!]!
}

type Query {
  user(id: ID!): User
}

# schema/post.gql
type Post {
  id: ID! @model
  content: String! @model
}

extend type Query {
  post(id: ID!): Post
}
```

```ts
// resolvers/user.ts
const userResolver = {
  Query: {
    user(parent, args, ctx) {},
  },
  User: {
    posts(parent, args, ctx) {},
  }  
}

// resolvers/post.ts
const postResolver = {
  Query: {
    post(parent, args, ctx) {},
  }
}
```

Based on nitrogql's default behavior, a single type named "Resolvers" is generated. Therefore, when splitting the resolver as shown above, I understand it's challenging to match the types properly.

Do you have any suggestions or solutions?

**Comment by uhyo** [comment]
Thanks for question! 😀 

For partial resolver definitions I'd recommend creating a helper function to get contextual typing.

```ts
function partialResolvers<
  R extends Partial<{
    [K in keyof Resolvers<{}>]: Partial<Resolvers<{}>[K]>;
  }>
>(resolvers: R): R {
  return resolvers;
}

const userResolver = partialResolvers({
  Query: {
    user(parent, args, ctx) {},
  },
  User: {
    posts(parent, args, ctx) {},
  }  
});

const postResolver = partialResolvers({
  Query: {
    post(parent, args, ctx) {},
  }
};
```

Then, do another TypeScript magic to ensure type safety when merging all resolvers.

```ts
type UnionToIntersection<U> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never;

function mergeResolvers<
  const Rs extends readonly Partial<{
    [K in keyof Resolvers<{}>]: Partial<Resolvers<{}>[K]>;
  }>[]
>(
  resolvers: Rs
): {
  [K in keyof Resolvers<{}>]: UnionToIntersection<
    Rs[number] extends infer U
      ? U extends Record<K, infer V>
        ? V
        : never
      : never
  > & {};
} {
  const result = {} as Record<string, Record<string, unknown>>;
  for (const resolver of resolvers) {
    for (const [key, value] of Object.entries(resolver)) {
      if (result[key] === undefined) {
        result[key] = value;
      } else {
        Object.assign(result[key], value);
      }
    }
  }
  return result as any;
}

const resolvers: Resolvers<{}> = mergeResolvers([
  userResolver,
  postResolver,
]);
```

After writing this I noticed that this may be too magical. Maybe we should also include above helpers to generated TypeScript code. 😅

**Comment by uhyo** [comment]
Since we made `Resolvers` a generic type, it seems that we can't bundle above helper with generated code. 🥲 
Instead this will be displayed in a guide page in the docs.

**Comment by uhyo** [comment]
A new page in the docs describes the solution mentioned above. Feel free to report issues if you find any problem. :pray:

https://nitrogql.vercel.app/guides/organizing-resolver-definitions
