### ISSUE TITLE
Support graphql-import plugin (or similar function)

### ISSUE THREAD

**Issue by tomocrafter** [uhyo/nitrogql#20]
Hi, thank you for developing this great tool for typescript and graphql !
I wonder if graphql-import will be supported or planned. I think it will be much easier to add than supporting fragment colocation.
https://the-guild.dev/graphql/tools/docs/schema-loading#using-import-expression

**Comment by uhyo** [comment]
Thank you for suggestion! The `#include` syntax looks good.

I've been looking for a good syntax for expressing imports in `.graphql`. Maybe I can go with this one.

By the way, do you want this to be supported for *schema* loading or *operation* loading (or both)?

**Comment by uhyo** [comment]
Thank you for your patience! The `#import` syntax is available in nitrogql 1.4.0. Please try 🙂 

See also: https://nitrogql.vercel.app/blog/release-1.4

**Comment by tomocrafter** [comment]
I'm beyond words with happiness. Thank you so much.
I will definitely try using this feature at work.
