### ISSUE TITLE
Support exporting fragment as document

### ISSUE THREAD

**Issue by tomocrafter** [uhyo/nitrogql#35]
graphql-let supports exporting fragments as documents with gql, and we need to add this support to nitrogql as well in order to successfully migrate to nitrogql. It would be beneficial to have this feature as an optional toggle, but it seems that implementing it will take some time.

https://github.com/piglovesyou/graphql-let/blob/d7d9f4310ea5a3483ecbbcdb9c555d56440bf9f1/src/__snapshots__/loader.test.ts.snap#L192

**Comment by uhyo** [comment]
Thank you for suggestion 🙂 

I may be able to work on this, but I don't really get how one would use the generated fragment documents...

**Comment by tomocrafter** [comment]
Thank you for reply and I am happy to hear that you can maybe work on this.
In apollo client, there are read/write method for overwrite the only specific part of cache by using fragment document.

**Comment by uhyo** [comment]
Oh I see 🙂 thanks, then I think it's worth addition.

**Comment by uhyo** [comment]
@tomocrafter Hi, I added support for exporting fragments as documents. There is also a new `fragmentVariableSuffix` option.
This time I released it as `1.6.0-beta.0` in order to avoid frequent version bump. Thanks 🙂
