### ISSUE TITLE
Culling unused fragment from query operation document

### ISSUE THREAD

**Issue by tomocrafter** [uhyo/nitrogql#38]
graphql-ruby throws error when fragment(s) in query is not used in query operation.
https://github.com/rmosolgo/graphql-ruby/blob/5eac86139138332d17d4eb5ea3f59ae8e0aa8cfb/lib/graphql/static_validation/rules/fragments_are_used.rb#L22

but nitrogql includes all fragment that defined in .graphql file:
https://github.com/uhyo/nitrogql/blob/b8bfc822e5bd0289df8150ae966af044c0a38859/crates/printer/src/operation_js_printer/visitor.rs#L51

It should collect all fragment that query operation depends on and only include those fragment in document node to avoid this error and it also reduces bandwidth eventually.

**Comment by uhyo** [comment]
Thanks for reporting! 😇 This definitely needs improvement.

**Comment by uhyo** [comment]
Hi there. This one's been released as `1.6.0-beta.1`. Please try 😇
