### ISSUE TITLE
Support `.ts` for config file

### ISSUE THREAD

**Issue by dqn** [uhyo/nitrogql#4]
And I hope that config type will be provided.

**Comment by uhyo** [comment]
Thank you, I have to figure out how to execute `.ts` from Rust though 😇

**Comment by dqn** [comment]
One way is to separate core and CLI, which is what Rspack does. However, if you don't like this way, you can consider other ways or close this 🥲

**Comment by uhyo** [comment]
For now, `.js` is supported and config type is provided by `@nitrogql/cli`. Full support for `.ts` is pending 🥲 :pray:

**Comment by uhyo** [comment]
Fixed in 1.2 🙂
