### ISSUE TITLE
How to test react component with jest

### ISSUE THREAD

**Issue by tomocrafter** [uhyo/nitrogql#48]
Hi, Thank you always for making this great library.
This might be question rather than an issue.

So, how to test React component that imports .graphql file on jest. since graphq-let has jestTransformer.ts:
https://github.com/piglovesyou/graphql-let/blob/a5e95fa9d724c9885230c56e804116c84a5fc08d/src/jestTransformer.ts

What is the replacement for nitrogql?

Thank you so much!

**Comment by uhyo** [comment]
There's no alternative for jest transformer now. I need to implement one. 😇 

Implementation should be just tens of lines of code, so I don't think it will take much time. :pray:

**Comment by tomocrafter** [comment]
Thank you for looking into it.
I also trying to achive it by re-using `@nitrogql/graphql-loader` in transformer. but I would like to see that being implemented as part of official.

**Comment by uhyo** [comment]
Yeah looking at `@nitrogql/graphql-loader` should be very helpful for implementing something similar. Official implementation should come out soon 🙂

**Comment by uhyo** [comment]
Hi, I released `@nitrogql/jest-transform` that should satisfy your use case. Please try v1.7.0-beta.2 🙂
We might make further improvements before the stable 1.7.0 release.
